// examples/main-react/src/pages/Vue3Demo.js
import React from "react";
import hostMap from "../hostMap";
import WujieReact from "wujie-react";
import { useNavigate, useLocation } from "react-router-dom";

export default function Vue3Demo() {
  const location = useLocation();
  const navigation = useNavigate();
  const path = location.pathname.replace("/vue3Demo-sub", "").replace("/vue3Demo", "");////
  const vue3DemoUrl = hostMap("//localhost:7800/");
    // 告诉子应用要跳转哪个路由
  path && WujieReact.bus.$emit("vue3-router-change", path);
  const props = {
    jump: (name) => {
      navigation(`/${name}`);
    },
  };
  return (
    <WujieReact
      width="100%"
      height="100%"
      name="vue3Demo"
      url={vue3DemoUrl}
      sync={!path}
      props={props}
    ></WujieReact>
  );
}

// examples/main-vue/src/views/Vue3Demo.vue
<template>
  <!--保活模式，name相同则复用一个子应用实例，改变url无效，必须采用通信的方式告知路由变化 -->
  <WujieVue width="100%" height="100%" name="vue3Demo" :url="vue3DemoUrl" :sync="true"></WujieVue>
</template>

<script>
import hostMap from "../hostMap";
export default {
  data() {
    return {
      vue3DemoUrl: hostMap("//localhost:7800/"),
    };
  },
};
</script>

<style lang="scss" scoped></style>
